### ISSUE TITLE
Only the intersection of fields (of a TS model and the SDL type definition) should be generated for the resolver types. 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/graphqlgen#108]
## Description

Only the intersection of fields (of a TS model and the SDL type definition) should be generated for the resolver types. 

#### TypeScript model in `models.ts`

```typescript
export interface Post {
  id: string
  title: string
  content: string
  published: boolean
  authorId: string
}
```

#### SDL type in `schema.graphql`

```graphql
type Post {
  id: ID!
  title: String!
  content: String!
  published: Boolean!
  author: User!
}
```

#### `graphqlen.yml`

```yml
language: typescript

input:
  schema: ./src/schema.graphql        # GraphQL schema
  context: ./src/types.ts:Context     # Defines the context object passed through the resolver chain
  models:                             # Model types from the `schema` mapped to TS definitions
    User: ./src/models.ts:User
    Post: ./src/models.ts:Post

output:
  types: ./src/generated/graphqlgen.ts
  models: ./src/tmp/models.ts
  resolvers: ./src/tmp/resolvers.ts
```

#### Default resolvers for in generated `graphqlgen.ts`

```ts
export const defaultResolvers = {
    id: parent => parent.id,
    title: parent => parent.title,
    content: parent => parent.content,
    published: parent => parent.published,
    authorId: parent => parent.authorId
};
```

## Expected results

The `authorId` resolver should not be there as it's not part of the GraphQL schema.

## Actual results

It is there.
