### ISSUE TITLE
Better models configuration/workflow

### ISSUE THREAD

**Issue by Weakky** [prisma/graphqlgen#162]
## Description

Currently, all the model definitions have to be defined in the `graphqlgen.yml` configuration file, which can become cumbersome when dealing with too much types.

## Proposal

Introspect typescript files and look for matching names between application schema type names and model definitions names.

The `models` property could look like this:

```yml
models:
  files:
    - ./src/generated/prisma-client
    - ./src/types
  override:
    User: ./src/generated/prisma-client/index.ts:UserNode
```
