### ISSUE TITLE
Add model default name configuration option

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#176]
The default assumption is that a model has the same name as the GraphQL type. In some code bases there is a different default name, so this should be configurable via the following configuration option:

```yml
models:
  defaultName: "{typeName}Node"
  files:
    - ./src/generated/prisma-client
```
