### ISSUE TITLE
Allow for wildcard file syntax for `models.files` config option

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#177]
For codebases that split up models across files, we should add support for a wildcard file syntax for the `models.files` config option.

Examples:

```yml
models:
  files:
    - ./src/models/*.ts

# or 
models:
  files:
    - ./src/**/*.ts
```
