### ISSUE TITLE
Invalid graphqlgen.yml file -  .models['files'] should be string. type: string

### ISSUE THREAD

**Issue by sapkra** [prisma/graphqlgen#180]
## Description
`graphqlgen` is not wokring anymore after switching to `models.files` syntax

## Steps to reproduce
```yaml
models:
  files:
    - ./src/generated/prisma-client
    - ./src/types
```

## Expected results
No error is thrown

## Actual results
```bash
Invalid graphqlgen.yml file
.models['files'] should be string. type: string
```
## Versions
- graphqlgen: 0.2.4
- OS name and version: Mac OS 10.14
