### ISSUE TITLE
Move defaultName to file level

### ISSUE THREAD

**Issue by timsuchanek** [prisma/graphqlgen#190]
When having a defaultName like `${typeName}Node` globally defined right now for all files, as we do in the current definition format, we neglect an important use-case:
Having different defaultNames per file.

To solve this, we move the `defaultName` to the `file` level.
So instead of this:
```yaml
models:
  defaultName: '${typeName}Node'
  files:
    - ./src/types.ts
    - ./src/generated/prisma-client
```
we now have this:
```yaml
models:
  files:
    - ./src/types.ts
    - path: ./src/generated/prisma-client
      defaultName: '${typeName}Node'
```
whereas a file can either be a string or an object containing the `path` and the `defaultName`.

In order to make this even more flexible and circumvent unwanted repetition, we introduce globbing support for file names. That means file names of this form we be supported: `./src/models/*.ts`
