### ISSUE TITLE
Supporting modularized graphql schemas

### ISSUE THREAD

**Issue by nomadoda** [prisma/graphqlgen#201]
I keep my graphql schemas and models in a modular file structure:

src/
—modules/
——user/
———user.graphql
———user.model.ts
——post/
———post.graphql
———post.model.ts

My graphqlgen.yml

```
language: typescript

schema: ./src/modules/**/*.graphql
context: ./src/typings/schema.d.ts:Context
models:
  files:
    - ./src/modules/**/*.model.ts

output: ./src/generated/graphqlgen.ts

resolver-scaffolding:
  output: ./src/generated/tmp-resolvers/
  layout: file-per-type

```

***throws***: *'The schema file* ./src/modules/**/*.graphql *does not exist'*
