### ISSUE TITLE
Incorrect import paths in generated file

### ISSUE THREAD

**Issue by affanshahid** [prisma/graphqlgen#207]
## Description
I am trying to generate resolver types with the following config:

```yml
language: typescript

schema: ./src/schema.graphql
context: ./src/types.ts:Context

models:
  files:
    - ./src/types.ts

output: ./src/resolvers/types.ts
```

The generated file is typed correctly but the imports at the top of the file use back-slahses (`\`) in the import path which is incorrect. I am on windows if that's relevant:

![image](https://user-images.githubusercontent.com/17955210/47603106-afdab000-da00-11e8-8efb-834592a3e6bb.png)

## Steps to reproduce
Add a similar config and run graphqlgen

## Expected results
The import paths should be correct (i.e use forward slashes)

## Actual results
Screenshot shared above

## Versions

- graphqlgen: 0.2.12
- OS name and version: Windows 10
