### ISSUE TITLE
Enum handling

### ISSUE THREAD

**Issue by affanshahid** [prisma/graphqlgen#213]
If I add an enum to my gql schema with a matching enum in my models file, the tool throws an error saying a model was not found. If I change the type of the enum (in my models) to interface, then it works but obviously is broken.

TL;DR: The tool expects an interface model for an enum in the schema

**Comment by Weakky** [comment]
Hey 👋,

We're indeed currently not supporting `enums` defined in typescript files.

One current workaround would be to define your enums using union types instead of interfaces.

Given such an enum defined in your GraphQL schema:

```graphql
enum Color {
  RED,
  GREEN,
  BLUE
}
```
You could define such a type in your typescript file:
(Which is not perfect but better than an using an `interface`)

```ts
type Color = 'RED' | 'GREEN' | 'BLUE'
```

Bottom line: This is a known limitation that we'll have to fix 🙏

**Comment by affanshahid** [comment]
Thanks for the help! This excellent tool btw, great work.

**Comment by arielschiavoni** [comment]
Hi, I have a very similar issue. I use the config from the [typescript-graphql](https://github.com/prisma/prisma-examples/blob/master/typescript-graphql/graphqlgen.yml) 
prisma examples.

In order to make my resolver typecheck I have to use the following config `defaultName: '${typeName}Node'` in my **graphqlgen.yml** file.

```yml
models:
  files:
    - path: ./src/generated/prisma-client
      defaultName: '${typeName}Node'
```

Without `defaultName: '${typeName}Node'`

![image](https://user-images.githubusercontent.com/1364564/47676783-c7ab6300-dbbd-11e8-987c-1d421530ba63.png)

With `defaultName: '${typeName}Node'`

![image](https://user-images.githubusercontent.com/1364564/47676884-050ff080-dbbe-11e8-8441-39f2b1ed3d6a.png)

So far so good, however when I added enums to my schema I couldn't manage to make it work anymore.

The enum types are correctly generated by prisma.

**schema.graphql**
```graphql
enum LANG {
  EN
  DE
}
```

**prisma-client/index.ts**

```ts
export type LANG = "EN" | "DE";
```

However I get the error that the types are not defined.

![image](https://user-images.githubusercontent.com/1364564/47675960-9467d480-dbbb-11e8-8d9d-e8d82ed66af2.png)

I tried copy pasting the union type from the **prisma-client/index.ts** file into my own **models.ts** and added them to the `graphqlgen` config without the `defaultName` prop. But it also does not work.

```yml
models:
  files:
    - path: ./src/generated/prisma-client
      defaultName: '${typeName}Node'
    - path: ./src/models.ts
```

**Comment by sidroopdaska** [comment]
Is there a timeline on this being fixed?

**Comment by Weakky** [comment]
Hey 👋,

This is indeed a bug we need to fix. The reason for this behavior at the moment is because of the `defaultName: '${typeName}Node'` property. Enums generated by `prisma-client` do not have this pattern name and are therefore ignored.

One workaround would be to configure your `models` property of your `graphqlgen.yml` file such as:

```yml
models:
  files:
    - ./src/generated/prisma-client
    - path: ./src/generated/prisma-client
      defaultName: '${typeName}Node'
```

This way, `graphqlgen` is going to proceed like this:

- Look for typescript models that have the same names as your graphql types (eg: `Role` model mapping to `Role` graphql type)
- If none found, look for typescript models that matches graphql type names following the pattern `${typeName}Node` (eg: `UserNode` model mapping to `User` graphql type).
