### ISSUE TITLE
Idea: gRPC plugin

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#255]
It's a very common use-case to use GraphQL as a gateway (as opposing to a GraphQL monolith/service) in front of other services (e.g. gRPC, Thrift, ...). I'd like to explore the possible workflows of using `graphqlgen` to auto-generate/auto-scaffold resolvers mapping to gRPC services.

My current idea would be to create a scaffolding plugin (see #84) which instead of scaffolding a resolver that throws an error, actually scaffolds a runnable resolver that calls out to the corresponding gRPC service.

The needed configuration/mapping could either be provided via some namespace in `graphqlgen.yml` or partially in the application schema via schema directives. Here's an idea how the config could look like in the `graphqlgen.yml`

```yml
# ...

resolver-scaffolding:
  output: ./src/generated/tmp-resolvers/
  layout: file-per-type
  plugins:
    grpc:
      input: ./my-service.proto
      resolvers:
        Query:
          feed: GetPosts
        Mutation:
          createDraft: NewDraft
```
