### ISSUE TITLE
Importing types from generated prisma-schema.ts 

### ISSUE THREAD

**Issue by tkawik-dbk** [prisma/graphqlgen#298]
Is there any way of avoiding duplication of information in the schemas? I mean I would like to reuse graphql schema generated by prisma for populating schema.graphql. Currently generated schema is only available inside prisma-schema.ts and I'm not sure if I can import import it to schema.graphql?

For example in https://github.com/prisma/prisma-examples/tree/master/typescript-graphql the schema for the User is duplicated in prisma/datamodel.prisma and in src/schema.graphql. 

And maybe related thing. I was completely lost when I was looking for typescript-prisma example project, because I also found https://github.com/prisma/graphql-prisma-typescript, but it was not properly working with my prisma's models. Shouldn't that project disappear to eliminate confusion?

**Comment by Weakky** [comment]
Hey there,

That question is related to `prisma` and not `graphqlgen` directly. Let me answer you anyway !

You can indeed import types from the schema generated by prisma. To do so, you need to add the following property to your `prisma.yml`:

```yml
generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client/
  - generator: graphql-schema # <-- Add graphql-schema generator
    output: ../src/generated/
``` 

Then, run `prisma generate`, which should create a `prisma.graphql` file.
Once this is done, just use the syntax provided by `graphql-import` to import the types from the `prisma.graphql` file.

It would rougly look like this:

```graphql
# import User from "./src/generated/prisma.graphql"

type Query {
  user(id: ID!): User # <-- type import from the schema
}
```

And voila !
