### ISSUE TITLE
graphqlgen issues

### ISSUE THREAD

**Issue by steida** [prisma/graphqlgen#351]
1) .tsx files are ignored for some reason. .ts files work.

```
language: typescript

schema: ./schema.graphql
context: ./types.ts:Context
models:
  files:
    - ./types.ts

output: ./api/generated/graphqlgen.ts

resolver-scaffolding:
  output: ./api/generated/tmp-resolvers/
  layout: file-per-type
```

2) IFoo naming does not work.

Interfaces should be prefixed with I (Hungarian notation). It's checked by tslint and IMHO it is a good rule. It prevents naming clashes. Foo vs IFoo.

![screenshot 2018-12-18 at 00 00 08](https://user-images.githubusercontent.com/66249/50121105-fb1e7b80-0257-11e9-93c5-d3f97dc7c3dc.png)

Therefore, we have to tslint ignore it.
