### ISSUE TITLE
Import typescript file in schema: Syntax Error: Cannot parse the unexpected character "."

### ISSUE THREAD

**Issue by devautor** [prisma/graphqlgen#436]
How do I import a typescript file as the schema in `graphqlgen` configuration. 

I am using graphql-code-generator to generate types from my schema using:
`schema: http://localhost:4000/graphql`
Then, as I am trying to use `graphqlgen` to generate resolvers from these generated types and the schema.

I am getting this error:
```
G:\server\prod\apollo-server>graphqlgen
Error occurred while reading schema: Syntax Error: Cannot parse the unexpected character ".".

GraphQL request (1:1)
1: ./src/makeExecutableSchema.ts
   ^


G:\server\prod\apollo-server>
```

My `graphqlgen.yml` is:
```
# The target programming language for the generated code
language: typescript

# The file path pointing to your GraphQL schema
schema: ./src/makeExecutableSchema.ts

# Type definition for the resolver context object
context: ./src/context.ts:Context

# Map SDL types from the GraphQL schema to TS models
models:
  files:
    #- ./src/generated/prisma-client-ts/index.ts
    - ./src/types.d.ts

# Generated typings for resolvers and default resolver implementations
# Please don't edit this file but just import from here
output: ./src/generated/graphqlgen.ts

# Temporary scaffolded resolvers to copy and paste in your application
resolver-scaffolding:
  output: ./src/generated/tmp-resolvers/
  layout: file-per-type

```

**Comment by jasonkuhrt** [comment]
👋 

Can you share the contents of `./src/makeExecutableSchema.ts`?

**Comment by devautor** [comment]
Hello @jasonkuhrt Sure, here is my `./src/makeExecutableSchema.ts`:

```
/**
 * Makes executable schema for Apollo server API
 * from typedefs and resolvers, and adds permissions middleware
 */

import { makeExecutableSchema } from "apollo-server";
import typeDefs from "./schema";
//import { resolvers } from "./resolvers";
// import all scalar resolvers
import OKGGraphQLScalars from "@okgrow/graphql-scalars";

import { applyMiddleware } from "graphql-middleware";
//import permissions from "./auth/permissions";

const schema = makeExecutableSchema({
  typeDefs: typeDefs,
  resolvers: {
    ...OKGGraphQLScalars
  }
});

// with auth permission middleware, using graphql-shield
export default () => {
  // console.log(`Applying permissions middleware...`);
  // return applyMiddleware(schema, permissions);
  return applyMiddleware(schema);
};
```

And, here is my `./src/schema.ts`:

```
// Graphql schema of the server API

import { gql } from "apollo-server";
// import all scalars
import { OKGScalarDefinitions } from "@okgrow/graphql-scalars";

// importing typescript files, each is gql`...` extending types Query, Mutation, Subscription
import sharedSchema from "./schema/shared";  
import postSchema from "./schema/post";
import storeSchema from "./schema/store";
import customerSchema from "./schema/customer";
import collectionSchema from "./schema/collection";
import productVariantSchema from "./schema/productVariant";

const blankSchema = gql`
  type Query {
    _blank: String
  }

  type Mutation {
    _blank: String
  }

  type Subscription {
    _blank: String
  }
`;

const schema = [
  blankSchema,
  ...OKGScalarDefinitions,
  sharedSchema,
  postSchema,
  storeSchema,
  customerSchema,
  collectionSchema,
  productVariantSchema
];

export default schema;
```

**Comment by jasonkuhrt** [comment]
schema: ./src/makeExecutableSchema.ts 

Should be

schema: ./src/schema.ts

**Comment by devautor** [comment]
Thanks for the reply @jasonkuhrt but that too gives the same error.
```
Error occurred while reading schema: Syntax Error: Cannot parse the unexpected character ".".

GraphQL request (1:1)
1: ./src/schema.ts
```

**Comment by jasonkuhrt** [comment]
@devautor thanks for confirming, its a step in the right direction but clearly still something wrong.

**Comment by devautor** [comment]
Thanks @jasonkuhrt for your patience! Yes, I am using `"graphqlgen": "^0.6.0-rc4"` (copied from `package.json`).

**Comment by jasonkuhrt** [comment]
@devautor same to you :) I'll try to take a closer look at this tonight or failing that in the coming days.

**Comment by devautor** [comment]
Oh, sure! I hope you could find time for this tonight, or sooner than later (I have my timeline set to "Write resolvers" from today). [I understand that you have n things to do :) ]

**Comment by jasonkuhrt** [comment]
Hey @maticzav on your end are you experiencing any issues having graphqlgen get schema from your TS module?

**Comment by devautor** [comment]
Hi @jasonkuhrt Thank you so much for your fix; but I am not able to get it running still, am I doing something wrong here:

```
G:\apollo\prod\apollo-server>npm i -D graphqlgen
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ graphqlgen@0.6.0-rc5
updated 2 packages in 17.991s

G:\apollo\prod\apollo-server>graphqlgen
Error occurred while reading schema: Syntax Error: Cannot parse the unexpected character ".".

GraphQL request (1:1)
1: ./src/schema.ts
   ^


G:\apollo\prod\apollo-server>graphqlgen
Error occurred while reading schema: Syntax Error: Cannot parse the unexpected character ".".

GraphQL request (1:1)
1: ./src/makeExecutableSchema.ts
   ^


G:\apollo\prod\apollo-server>
```

**Comment by jasonkuhrt** [comment]
I only just published the new version. Give [0.6.0-rc6](https://github.com/prisma/graphqlgen/releases/tag/0.6.0-rc6) a try.

**Comment by devautor** [comment]
Sorry @jasonkuhrt my bad! Trying with rc6 is still producing the same error to me:

```
G:\apollo\prod\apollo-server>npm i -D graphqlgen
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ graphqlgen@0.6.0-rc6
added 1 package and updated 2 packages in 29.478s

G:\apollo\prod\apollo-server>graphqlgen
Error occurred while reading schema: Syntax Error: Cannot parse the unexpected character ".".

GraphQL request (1:1)
1: ./src/makeExecutableSchema.ts
   ^


G:\apollo\prod\apollo-server>graphqlgen
Error occurred while reading schema: Syntax Error: Cannot parse the unexpected character ".".

GraphQL request (1:1)
1: ./src/schema.ts
   ^


G:\apollo\prod\apollo-server>
```

**Comment by jasonkuhrt** [comment]
Can you show me the output of:

```
cat ./src/schema.ts
```

And then, what happens if you try this:
```yml
# update your graphqlgen.yml to have this field:
schema: test-schema.graphql
```
```
> echo 'type Query {\n  a: String\n} > test-schema.graphql
> graphqlgen
```

**Comment by devautor** [comment]
Hello @jasonkuhrt I had shared `src/schema.ts` above, should I paste it here again? Also, following steps you have asked to test with a graphql file, I do get successful generation:

`src/test-schema.graphql` is:
```
type Query {
  a: String
}
```

`graphqlgen.yml` is:
```
# The target programming language for the generated code
language: typescript

# The file path pointing to your GraphQL schema
#schema: ./src/schema.ts
schema: ./src/test-schema.graphql

# Type definition for the resolver context object
context: ./src/context.ts:Context

# Map SDL types from the GraphQL schema to TS models
models:
  files:
    #- ./src/generated/prisma-client-ts/index.ts
    - ./src/types.d.ts

# Generated typings for resolvers and default resolver implementations
# Please don't edit this file but just import from here
output: ./src/generated/graphqlgen.ts

# Temporary scaffolded resolvers to copy and paste in your application
resolver-scaffolding:
  output: ./src/generated/tmp-resolvers/
  layout: file-per-type

```
Output is: 
```
G:\apollo\prod\apollo-server>graphqlgen
Resolver interface definitons & default resolvers generated at ./src/generated/graphqlgen.ts
Resolvers scaffolded at ./src/generated/tmp-resolvers/

G:\apollo\prod\apollo-server>
```

**Comment by maticzav** [comment]
hey @devautor 👋 Could you briefly explain how the list as a schema thing works? I haven’t seen it before but it looks very interesting.

@jasonkuhrt, `graphqlgen` generates types correctly in my project. Haven’t pushed it yet though.

**Comment by devautor** [comment]
Hey @maticzav a fan here :) 
I am following the docs for graphql-tools (Apollo server) from here: ["typeDefs is a required argument and should be an GraphQL schema language string or array of GraphQL schema language strings ... The order of the strings in the array is not important, but it must include a schema definition."](https://www.apollographql.com/docs/graphql-tools/generate-schema.html#makeExecutableSchema)

Kindly let me know if I have done something lazy here :)

P.S. BTW I was about to message you on twitter regarding `graphql-shield` :)

**Comment by jasonkuhrt** [comment]
@devautor since I don't have access to your project, and since you now have a hyper-minimal example schema working, can you start from the tester I gave you and incrementally make it be like yours, testing `graphqlgen` each time, the idea being we'll get a pinpoint on exactly what causes your case to break.

**Comment by devautor** [comment]
@jasonkuhrt I recall that the minimal example I got working was from a graphql file, and couldn't get one working from a ts file. But, I understand and appreciate your point. I will try to do that (maybe it could take time, since I am pressed down by a huge schema :) )

**Comment by jasonkuhrt** [comment]
@devautor what happens with (ts version):

```
> echo 'type Query {\n  a: String\n} > test-schema.ts
> graphqlgen
```

**Comment by devautor** [comment]
@jasonkuhrt I am sorry that I didn't report that... Here's what I get:

```
G:\apollo\prod\apollo-server>graphqlgen
Error occurred while reading schema: Syntax Error: Cannot parse the unexpected character ".".

GraphQL request (1:1)
1: ./src/test-schema.ts
   ^


G:\apollo\prod\apollo-server>
```

My `test-schema.ts` is:
```
import { gql } from "apollo-server";

const typeDefs = gql`
  type Query {
    a: String
  }
`;

export default typeDefs;
```

And, my `graphqlgen.yml` is:

```
# The target programming language for the generated code
language: typescript

# The file path pointing to your GraphQL schema
#schema: ./src/schema.ts
schema: ./src/test-schema.ts

# Type definition for the resolver context object
context: ./src/context.ts:Context

# Map SDL types from the GraphQL schema to TS models
models:
  files:
    #- ./src/generated/prisma-client-ts/index.ts
    - ./src/types.d.ts

# Generated typings for resolvers and default resolver implementations
# Please don't edit this file but just import from here
output: ./src/generated/graphqlgen.ts

# Temporary scaffolded resolvers to copy and paste in your application
resolver-scaffolding:
  output: ./src/generated/tmp-resolvers/
  layout: file-per-type

```
